config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'
  resources :employees
  resources :organizations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
   
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :employe_id, :email, :emp_type, :organization_id)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :phone, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :employeId %>
    <%= form.text_field :employe_id %>
  </div>
 <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :type %>
   <%= form.select(:emp_type, options_for_select([["admin", "1"], ["employee level 1", "2"], ["employee level 2", "3"]]))%>
  </div>

  <div class="field">

    <%= form.label :organizationId %>
    <%= form.text_field :organization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default">

  <form class="form-inline">
   
    <%= link_to 'Show Employee',employees_path,:class => "btn  navbar-btn"%> ||
    <%= link_to 'Show Organization', organizations_path, :class => "btn  navbar-btn"%>

     </form>
 
</nav>

</br></br>

<h1>Employees</h1>

<div class="table-responsive">
<table class="table table-bordered table-hover">
  <thead>
    <tr class="warning">
    <th class="text-center">ID</th>
      <th class="text-center">Name</th>
      <th class="text-center">Employe</th>
      <th class="text-center">Email</th>
      
      <th class="text-center">Organization Id</th>
      <th class="text-center" colspan="4">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
      <td class="bg-primary"><%= employee.id %></td>
        <td class="bg-danger"><%= employee.name %></td>
        <td class="bg-info"><%= employee.employe_id %></td>
        <td class="bg-success"><%= employee.email %></td>
        
       
        <td class="bg-danger"><%= employee.organization_id %></td>
        <td><%= link_to 'Show', employee, :class => "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= will_paginate @employees, {:style=>'font-size: 150%;'} %>

<br><br>

<%= link_to 'New Employee', new_employee_path, {:style=>'color:	#CD5C5C;text-decoration: underline;font-size: 180%;'}  %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<% user1 =  @employee.organization %>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Employe:</strong>
  <%= @employee.employe_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @employee.emp_type %>
</p>
<p>
  <strong>Oranisation Id</strong>
  <%= @employee.organization_id %>
</p>
<br><br><br>
<p>Organization details</p>

<div class="table-responsive">
<table class="table table-bordered table-hover">
<thead>
<tr class="info">
<th class="text-center">Name </th>
<th class="text-center">Phone</th>
<th class="text-center">City</th>
</tr>
</thead>
<tr class="warning">

<td>  <%= user1.name%></td>
  <td><%= user1.phone%> </td>
  <td><%= user1.city%> </td>
</tr>
</table>
</div>
</br></br>



<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assessment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default">

  <form class="form-inline">
   
    <%= link_to 'Show Employee',employees_path,:class => "btn  navbar-btn"%> ||
    <%= link_to 'Show Organization', organizations_path, :class => "btn  navbar-btn"%>

     </form>
 
</nav>

</br></br>


<h1>Organizations</h1>
<div class="table-responsive">
<table class="table table-bordered table-hover">
  <thead>
    <tr class="success">
    <th class="text-center">Organisation ID</th>
      <th class="text-center">Name</th>
      <th class="text-center">Phone</th>
      <th class="text-center">City</th>
      <th class="text-center" colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr class="warning">
      <td><%= organization.id %></td>
        <td><%= organization.name %></td>
        <td><%= organization.phone %></td>
        <td><%= organization.city %></td>
        <td><%= link_to 'Show', organization, :class => "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

</br></br>

<%= will_paginate  @organizations,  {:style=>'font-size: 150%;'}%>
<br><br>

<%= link_to 'New Organization', new_organization_path, {:style=>'color:	#008000;text-decoration: underline;font-size: 150%;'}  %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>
<% user1 =  @organization.employees %>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>
<div class="table-responsive">
<table class="table table-bordered table-hover">
<thead> 
<tr class="info">
<th class="text-center"> Emp_Id </th>
<th class="text-center"> Name </th>
<th class="text-center"> Email </th>
</tr>
</thead>
<% user1.each do |item| %>   
  <tr class="warning">
  
     <td> <%= item.employe_id %> </td>   
     <td> <%= item.name %></td>
     <td> <%= item.email %> </td>   
    

   
     
     </tr>
     <%end %>
     </table>
     </div>
     </br>
     </br>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>